### PR TITLE
Write out debug log by default

### PR DESCRIPTION
**Pull request by lusassl-msft**
We write out a debug log by default. We automatically delete the debug log if no script error occurs. You can find the debug log here: %programdata%\ExchangeTools\HealthChecker

### CODE REVIEW

**Comment by lusassl-msft** [comment]
> Does this throw off the Write-Errors logic? Thinking we have errors that weren't being handled by the script?

Think we change this part to capture bad Errors. What do you think?
**From:**
                if(!($goodError))
                {
                    $Error[$index] | Out-File ($Script:OutputFullPath) -Append
                }

**To:**
                if(!($goodError))
                {
		    Write-DebugLog $Error[$index]
                    $Error[$index] | Out-File ($Script:OutputFullPath) -Append
                }

**Comment by dpaulson45** [comment]
> > Does this throw off the Write-Errors logic? Thinking we have errors that weren't being handled by the script?
> 
> Think we should change this part to capture bad Errors. Implementation does not change Write-Error logic at the moment.
> What do you think?
> **From:**
> if(!($goodError))
> {
> $Error[$index] | Out-File ($Script:OutputFullPath) -Append
> }
> 
> **To:**
> if(!($goodError))
> {
> Write-DebugLog $Error[$index]
> $Error[$index] | Out-File ($Script:OutputFullPath) -Append
> }

Yes, i think we should include the errors that might have occurred within the Debug Log.

**Comment by lusassl-msft** [comment]
Please see commit 3abf62d

**Comment by lusassl-msft** [comment]
Btw should we change it in the master function as well?

**Comment by dpaulson45** [comment]
> Btw should we change it in the master function as well?

Yeah, we should I am sure that will cause issues within Windows 2008 R2... i hate that version. So many issues.

**Pull request merged**
